version: 2.1

orbs:
  go: circleci/go@1.8.0

executors:
  go:
    docker:
      - image: cimg/go:1.21

jobs:
  build-and-test:
    executor: go
    parallelism: 4 
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - run: go install github.com/jstemmer/go-junit-report/v2@latest
      - go/save-cache
      - run:
          name: Download Previous Test Results
          command: |
            mkdir -p previous-test-results
            circleci tests glob "previous-test-results/*.xml" > previous-test-results/previous-results.txt
            while IFS= read -r line; do
              circleci tests store-previous-results --output-path "$line"
            done < previous-test-results/previous-results.txt
      - run:
          name: Matching Test Files
          command: |
            TESTS=$(circleci tests glob "*_test.go")
            echo "Test files: $TESTS"
            echo "Number of test files: $(echo "$TESTS" | wc -l)"
      - run:
          name: Split Tests
          command: |
            SPLIT_TESTS=$(circleci tests glob "*_test.go")
            echo "Split tests (before splitting): $SPLIT_TESTS"
            echo "Number of split tests before splitting: $(echo "$SPLIT_TESTS" | wc -l)"
            SPLIT_TESTS=$(circleci tests split --split-by=timings --files "$SPLIT_TESTS")
            echo "Split tests: $SPLIT_TESTS"
            echo "Number of split tests: $(echo "$SPLIT_TESTS" | wc -l)"
      - run:
          name: Run Tests
          command: |
            go test -v $(circleci tests glob "$SPLIT_TESTS") 2>&1 | go-junit-report -set-exit-code > /tmp/report.xml
      - store_test_results:
          path: /tmp/report.xml
      - store_artifacts:
          path: /tmp/report.xml

workflow:
  build-test:
    jobs:
      - build-and-test